/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { MyComponent as MyComponentElement } from "@stencil-test/stencil/my-component";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
export type MyComponentEvents = NonNullable<unknown>;
export declare const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents>;
