/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
