'use client';
/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
/* eslint-disable */
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@stencil-test/stencil/dist/components/my-component.js";
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
export const MyComponent = /*@__PURE__*/ createComponent({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {},
    defineCustomElement: defineMyComponent
});
